[app:main]
use = egg:mk_api

pyramid.reload_templates = true
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = en

# --- Database Config ---
# Ganti user, password, dan dbname sesuai PostgreSQL Anda
sqlalchemy.url = postgresql+psycopg2://postgres:asubek@localhost:5432/mk_db

[server:main]
use = egg:waitress#main
listen = localhost:6543

[loggers]
keys = root, mk_api, sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_mk_api]
level = DEBUG
handlers =
qualname = mk_api

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s:%(lineno)s][%(threadName)s] %(message)s